language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
prepublish:
  - npm run build
after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release" || exit 1
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
